# Generated by Django 5.2 on 2025-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceafterdiscount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dresses', 'Платья'), ('skirts', 'Юбки'), ('shirts', 'Рубашки'), ('blooses', 'Блузки'), ('pants', 'Брюки'), ('jackets', 'Куртки'), ('complects', 'Комплекты'), ('upper', 'Верхняя одежда'), ('toonics', 'Туники')], max_length=20, verbose_name='Категория'),
        ),
    ]
